name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  test:
    env:
      MIX_ENV: test
    runs-on: ubuntu-20.04
    name: Test (OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }})
    strategy:
      matrix:
        elixir: ["1.17", "1.16", "1.15", "1.14", "1.13", "1.12"]
        # All of the above can use this version. For details see: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        otp: [27, 26, 25, 24, 23, 22]
        exclude:
          # 1.12 is only compatible with OTP 22 - 24
          - elixir: "1.12"
            otp: "25"
          - elixir: "1.12"
            otp: "26"
          - elixir: "1.12"
            otp: "27"
          # 1.13 is only compatible with OTP 22 - 25
          - elixir: "1.13"
            otp: "26"
          - elixir: "1.13"
            otp: "27"
          # 1.14 is only compatible with OTP 23 - 26
          - elixir: "1.14"
            otp: "22"
          - elixir: "1.14"
            otp: "27"
          # 1.15 is only compatible with OTP 24 - 26
          - elixir: "1.15"
            otp: "22"
          - elixir: "1.15"
            otp: "23"
          - elixir: "1.15"
            otp: "27"
          # 1.16 is only compatible with OTP 24 - 26
          - elixir: "1.16"
            otp: "22"
          - elixir: "1.16"
            otp: "23"
          - elixir: "1.16"
            otp: "27"
          # 1.17 is only compatible with OTP 25 - 27
          - elixir: "1.17"
            otp: "22"
          - elixir: "1.17"
            otp: "23"
          - elixir: "1.17"
            otp: "24"
    steps:
      - uses: actions/checkout@v4
      - id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix test

  lint:
    runs-on: ubuntu-22.04
    name: Linting
    strategy:
      matrix:
        elixir: ["1.17"]
        otp: [27]
    steps:
      - uses: actions/checkout@v4
      - id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: PLT cache
        uses: actions/cache@v4
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            priv/plts
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix dialyzer
